backend:
  name: git-gateway
  branch: master

media_folder: "assets/img"
public_folder: "/assets/img"

collections:
  - name: "travel"
    label: "Travel"
    folder: "content/travel"
    create: true
    slug: "{{slug}}"
    media_folder: "../../assets/img/Travel"
    public_folder: "/assets/img/Travel"
    fields:
      - { label: "Image", name: "image", widget: "image", required: true }

  - name: "animals"
    label: "Animals"
    folder: "content/animals"
    create: true
    slug: "{{slug}}"
    media_folder: "../../assets/img/animals"
    public_folder: "/assets/img/animals"
    fields:
      - { label: "Image", name: "image", widget: "image", required: true }

  - name: "architecture"
    label: "Architecture"
    folder: "content/architecture"
    create: true
    slug: "{{slug}}"
    media_folder: "../../assets/img/architecture"
    public_folder: "/assets/img/architecture"
    fields:
      - { label: "Image", name: "image", widget: "image", required: true }

  - name: "deep1"
    label: "Deep Dropdown 1"
    folder: "content/deep-dropdown-1"
    create: true
    slug: "{{slug}}"
    media_folder: "../../assets/img/deep-dropdown-1"
    public_folder: "/assets/img/deep-dropdown-1"
    fields:
      - { label: "Image", name: "image", widget: "image", required: true }

  - name: "deep2"
    label: "Deep Dropdown 2"
    folder: "content/deep-dropdown-2"
    create: true
    slug: "{{slug}}"
    media_folder: "../../assets/img/deep-dropdown-2"
    public_folder: "/assets/img/deep-dropdown-2"
    fields:
      - { label: "Image", name: "image", widget: "image", required: true }

  - name: "deep3"
    label: "Deep Dropdown 3"
    folder: "content/deep-dropdown-3"
    create: true
    slug: "{{slug}}"
    media_folder: "../../assets/img/deep-dropdown-3"
    public_folder: "/assets/img/deep-dropdown-3"
    fields:
      - { label: "Image", name: "image", widget: "image", required: true }

  - name: "deep4"
    label: "Deep Dropdown 4"
    folder: "content/deep-dropdown-4"
    create: true
    slug: "{{slug}}"
    media_folder: "../../assets/img/deep-dropdown-4"
    public_folder: "/assets/img/deep-dropdown-4"
    fields:
      - { label: "Image", name: "image", widget: "image", required: true }

  - name: "deep5"
    label: "Deep Dropdown 5"
    folder: "content/deep-dropdown-5"
    create: true
    slug: "{{slug}}"
    media_folder: "../../assets/img/deep-dropdown-5"
    public_folder: "/assets/img/deep-dropdown-5"
    fields:
      - { label: "Image", name: "image", widget: "image", required: true }

  - name: "gallery"
    label: "Gallery"
    folder: "content/gallery"
    create: true
    slug: "{{slug}}"
    media_folder: "../../assets/img/gallery"
    public_folder: "/assets/img/gallery"
    fields:
      - { label: "Image", name: "image", widget: "image", required: true }

  - name: "nature"
    label: "Nature"
    folder: "content/nature"
    create: true
    slug: "{{slug}}"
    media_folder: "../../assets/img/nature"
    public_folder: "/assets/img/nature"
    fields:
      - { label: "Image", name: "image", widget: "image", required: true }

  - name: "people"
    label: "People"
    folder: "content/people"
    create: true
    slug: "{{slug}}"
    media_folder: "../../assets/img/people"
    public_folder: "/assets/img/people"
    fields:
      - { label: "Image", name: "image", widget: "image", required: true }

  - name: "sports"
    label: "Sports"
    folder: "content/sports"
    create: true
    slug: "{{slug}}"
    media_folder: "../../assets/img/sports"
    public_folder: "/assets/img/sports"
    fields:
      - { label: "Image", name: "image", widget: "image", required: true }